import { useQuery } from '@apollo/client';
import Head from 'next/head'
import {useMoralis, useMoralisQuery} from 'react-moralis';
import NFTBox from '../components/NFTBox.js';
import networkMapping from '../constants/networkMapping.json'
import GET_ACTIVE_ITEMS from '../constants/SubGraphQueries.js';

export default function Home() {
  const {isWeb3Enabled, chainId} = useMoralis();
  const chainIdString = chainId ? parseInt(chainId).toString() : '31337';

  // const {data: listedNfts, isFetching: fetchingListedNfts} = useMoralisQuery('ActiveItem', query => query.limit(10).descending("tokenId"));
  const marketPlaceAddress = networkMapping[chainIdString].NftMarketplace[0]

  const {loading, error, data: listedNfts } = useQuery(GET_ACTIVE_ITEMS)

  // console.log("listedNfts", listedNfts);
  // console.log("fetchingListedNfts", fetchingListedNfts);


  return (
    <div className="container mx-auto flex flex-wrap flex-col md:flex-row items-center">
      <Head>
        <title>NFT MarketPlace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        !isWeb3Enabled ? 
          <div className='flex-grow text-center font-bold text-slate-500 text-lg'>Please Connect Wallet</div>
          :
          loading ? <div className='flex-grow text-center font-bold text-slate-500 text-lg'>Loading...</div>
            :
              listedNfts.activeItems.length<1 ?
                <div className='flex-grow text-center font-bold text-slate-500 text-lg'>No NFTs Listed</div>
                :
                <div className="flex flex-wrap m-4 gap-2 justify-center">
                  {listedNfts.activeItems.map((listedNft, index) => {
                    const {price, nftAddress, tokenId, seller} = listedNft;
                    return(
                    
                      <NFTBox price={price} nftAddress={nftAddress} tokenId={tokenId} marketplaceAddress={marketPlaceAddress} seller={seller}  key={index}/>
                    
                  )}
                )}
        </div>

      }
    </div>
  )
}
